// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "gui.h"
static int fConnected = 0; 

Fl_Button *closeButton=(Fl_Button *)0;

static void cb_closeButton(Fl_Button*, void*) {
  exit(0);
}

Fl_Output *urlText=(Fl_Output *)0;

Fl_Button *browseButton=(Fl_Button *)0;

static void cb_browseButton(Fl_Button*, void*) {
  Fl_Native_File_Chooser fc;
	fc.title("Open");
	fc.type(Fl_Native_File_Chooser::BROWSE_DIRECTORY);
	switch ( fc.show() ) {
	case -1: break;	// Error
	case  1: break; 	// Cancel
	default:		// Choice
		fc.preset_file(fc.filename());
		folderText->value(fc.filename());
		fprintf(stderr, "open %s\n", fc.filename());
		break;
	};
}

Fl_Output *folderText=(Fl_Output *)0;

Fl_Light_Button *connectButton=(Fl_Light_Button *)0;

static void cb_connectButton(Fl_Light_Button*, void*) {
  if (!fConnected) {
	fConnected = online_client(folderText->value());
	if (fConnected) {
		browseButton->deactivate();
//		shareButton->value(1);
	}
} else {
	fConnected = offline_client();
	if (!fConnected) {
		browseButton->activate();
//		shareButton->value(0);
		urlText->value("");
	}
};
}

Fl_Box *infoStr=(Fl_Box *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(535, 110, "GetMyFil.es");
    w = o;
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { closeButton = new Fl_Button(455, 80, 75, 25, "Quit");
      closeButton->callback((Fl_Callback*)cb_closeButton);
    } // Fl_Button* closeButton
    { urlText = new Fl_Output(55, 45, 395, 25, "URL");
    } // Fl_Output* urlText
    { browseButton = new Fl_Button(455, 10, 75, 25, "Browse");
      browseButton->callback((Fl_Callback*)cb_browseButton);
    } // Fl_Button* browseButton
    { folderText = new Fl_Output(55, 10, 395, 25, "Folder");
    } // Fl_Output* folderText
    { connectButton = new Fl_Light_Button(455, 45, 75, 25, "Share");
      connectButton->selection_color(FL_RED);
      connectButton->callback((Fl_Callback*)cb_connectButton);
    } // Fl_Light_Button* connectButton
    { infoStr = new Fl_Box(5, 80, 445, 25, "ItsMyFile client");
    } // Fl_Box* infoStr
    o->size_range(535, 110, 535, 110);
    o->end();
  } // Fl_Double_Window* o
  return w;
}

void set_online() {
  fConnected = 1;
  browseButton->deactivate();
  //urlButton->value("Online");
  connectButton->value(1);
}

void set_offline() {
  fConnected = 0;
  browseButton->activate();
  //urlButton->value("Online");
  connectButton->value(0);
  urlText->value("");
}

void show_server_directory(char *dir) {
  urlText->value(dir);
}

void show_shared_directory(char *dir) {
  folderText->value(dir);
}
