/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_getmyfiles_gui_GetMyFilesActivity */

#ifndef _Included_com_getmyfiles_gui_GetMyFilesActivity
#define _Included_com_getmyfiles_gui_GetMyFilesActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_getmyfiles_gui_GetMyFilesActivity_ACTIVITY_CREATE
#define com_getmyfiles_gui_GetMyFilesActivity_ACTIVITY_CREATE 1L
#undef com_getmyfiles_gui_GetMyFilesActivity_NOTIFICATION_ID
#define com_getmyfiles_gui_GetMyFilesActivity_NOTIFICATION_ID 1L
/*
 * Class:     com_getmyfiles_gui_GetMyFilesActivity
 * Method:    connectClient
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_getmyfiles_gui_GetMyFilesActivity_connectClient
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_getmyfiles_gui_GetMyFilesActivity
 * Method:    disconnectClient
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_getmyfiles_gui_GetMyFilesActivity_disconnectClient
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
