// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Native_File_Chooser.H>
int online_client(const char *path); 
int offline_client(void); 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern Fl_Button *closeButton;
#include <FL/Fl_Output.H>
extern Fl_Output *urlText;
extern Fl_Button *browseButton;
extern Fl_Output *folderText;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *connectButton;
extern "C" { Fl_Double_Window* make_window(); }
extern "C" { void set_online(); }
extern "C" { void set_offline(); }
extern "C" { void show_server_directory(char *dir); }
extern "C" { void show_shared_directory(char *dir); }
#endif
