/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class technology_madisa_getmyfiles_External */

#ifndef _Included_technology_madisa_getmyfiles_External
#define _Included_technology_madisa_getmyfiles_External
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     technology_madisa_getmyfiles_External
 * Method:    connectClient
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_technology_madisa_getmyfiles_External_connectClient
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
